#!/bin/bash
set -e -x
echo "devopsagent1.devops.com" > /etc/hostname
hostname devopsagent1.devops.com
echo "172.31.88.168 puppetmaster.devops.com puppetmaster"  >> /etc/hosts
yum update -y
curl -k https://puppetmaster.devops.com:8140/packages/current/install.bash | sudo bash
